### ISSUE TITLE
URLs in Codelists

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#18] opened 2014-01-23 15:53 UTC
In this document, links are given to the source of codelists:
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdFNxVS1NdmpzSnR3aTBmUG1OWS1uZXc&usp=drive_web#gid=15

How should our codelists deal with these URLs. In this case the URL endpoints are not machine readable as such. Would that make a difference if they were?

**Comment by Bjwebb** [comment] 2014-03-04 12:26
This is a duplicate of https://github.com/IATI/IATI-Codelists/issues/4

**Closed as completed by Bjwebb** 2014-03-04 12:26 UTC
Labels: duplicate
